# Generated by Django 4.2.1 on 2023-05-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='api.image')),
            ],
        ),
    ]
